
jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory#change this to your database url
    password: caroline_654321 #change this to your database username
    username: root #change this to your database password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        spring:
          autoconfigure:
            exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
            mail:
              host: smtp.gmail.com
              port: 587
              username: tendaikawadza49@gmail.com
              password: wmosowxsyqtsqeld
              protocol: smtp
              tls: true
              properties.mail.smtp:
                auth: true
                starttls.enable: true

                ssl.trust: smtp.gmail.com

    application:
      name: support

      eureka:
        client:
          serviceUrl: defaultZone:http://localhost:8761/eureka/